### ISSUE TITLE
External Mangadex Links

### ISSUE THREAD

**Issue by linus727** [Sydiepus/mangadex-py#13]
Hey I founda bug that aborts the script. It seems that it cant handle external Manga Links. Chapter 1 has an external version and an internal, it should prefere the internal from mangadex. Chapter 2 should be skipped since its only external and so on...

See here in the example Manga:
https://mangadex.org/title/7e9a9b89-ea6a-494e-a611-dd3a2a753ca4/

```
getting uuid.
fetching manga info 'Title' 'description' 'status' based on your language setting.
No altTitles with that language found; using default title.
fetching chapters info 'available languages' 'available volumes if any' 'available chapters' 'total chapters (language independent)'.
-------------------------------------------
Kyosei Tensei
-------------------------------------------
fetching 'chapter list by language' 'total chapters by language.'
found 452 out of 20 for en
getting a server url to download the images from.
starting download
2 scanlation for chapter-1 found, selecting the 'best one'.
no images found for that chapter could be an external link.
Traceback (most recent call last):
  File "Z:\mangadex\mangadex-py.py", line 4, in <module>
    main()
  File "Z:\mangadex\mangadex_py\util.py", line 16, in main
    file_main(args.File, langwithindex, args.quality_mode, args.destination, args.max_threads)
  File "Z:\mangadex\mangadex_py\file_main.py", line 11, in file_main
    main(url_name[0], langWithIndex, quality_mode, Manga_main_dir, thread)
  File "Z:\mangadex\mangadex_py\main.py", line 28, in main
    download.main(title, chap_list, desc, status, quality_mode, base_url, volumes, Manga_main_dir, thread)
  File "Z:\mangadex\mangadex_py\download.py", line 63, in main
    chap_img = scanlation_group_selector(list_chap, quality_mode)
  File "Z:\mangadex\mangadex_py\chapters.py", line 145, in scanlation_group_selector
    images_list = images_list[:] + get_chapter_images([i], quality_mode)
TypeError: can only concatenate list (not "NoneType") to list
```

**Comment by Sydiepus** [comment]
i'm looking into the issue.

**Comment by linus727** [comment]
With the update i get this error:

```
C:\Users\Linus\Desktop\Mangadex\test\Neuer Ordner>python mangadex-py.py https://mangadex.org/title/c9bed72c-d680-4409-a954-5fdadde27b74
Traceback (most recent call last):
  File "C:\Users\Linus\Desktop\Mangadex\test\Neuer Ordner\mangadex-py.py", line 1, in <module>
    from mangadex_py.util import main
  File "C:\Users\Linus\Desktop\Mangadex\test\Neuer Ordner\mangadex_py\util.py", line 2, in <module>
    from .main import main as real_main
  File "C:\Users\Linus\Desktop\Mangadex\test\Neuer Ordner\mangadex_py\main.py", line 2, in <module>
    import mangadex_py.chapters as chapter
  File "C:\Users\Linus\Desktop\Mangadex\test\Neuer Ordner\mangadex_py\chapters.py", line 146
    if images == None :
                       ^
IndentationError: unindent does not match any outer indentation level

```

**Comment by Sydiepus** [comment]
hmmm it's working fine for me.
![image](https://user-images.githubusercontent.com/49863809/131914216-6e0386fe-b6a5-4b38-961d-ede1c4167f08.png)

**Comment by linus727** [comment]
yeah nvm I only edited the lines you edited and made a mistake I guess. After redownloading its working fine. my bad

**Comment by Sydiepus** [comment]
ohh it's okay we all make mistakes :)

**Comment by linus727** [comment]
Btw are you still looking into 3rd party downloads like redirections to mangaplus?

Also, I would like to recommend/suggest smth like a login function to get your followed chapter list on the start, then it would be easier to update your own collection if someone wants to do that.
I used this github to generate a follows list, maybe you can implement something alike.
https://github.com/StoicSun/MD-Follow-list

**Comment by Sydiepus** [comment]
yes i'm trying to get mangaplus links to work it'll take sometime because i'm trying to not use any 3rd party modules, as for the follow list it'll be a good enhancement i'll work on it.
