### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by linus727** [Sydiepus/mangadex-py#14]
Hey it seems since a new update from mangadex side the script is broken.

```
Initializing:  40%|████████████████████████████                                          | 2/5 [00:00<00:00,  4.17it/s]Traceback (most recent call last):
  File "C:\Users\Linus\Desktop\mangadex-py-master\mangadex-py.py", line 4, in <module>
    main()
  File "C:\Users\Linus\Desktop\mangadex-py-master\mangadex_py\util.py", line 19, in main
    file_main(args.File, langwithindex, args.quality_mode, args.destination, args.max_threads, args.zip_name)
  File "C:\Users\Linus\Desktop\mangadex-py-master\mangadex_py\file_main.py", line 11, in file_main
    main(url_name[0], langWithIndex, quality_mode, Manga_main_dir, thread, zip_name=zip_name)
  File "C:\Users\Linus\Desktop\mangadex-py-master\mangadex_py\main.py", line 16, in main
    language, volumes, _, totalchap = chapter.get_manga_chapters_info(uuid)
  File "C:\Users\Linus\Desktop\mangadex-py-master\mangadex_py\chapters.py", line 76, in get_manga_chapters_info
    get_info(resp)
  File "C:\Users\Linus\Desktop\mangadex-py-master\mangadex_py\chapters.py", line 56, in get_info
    for i in resp["results"] :
KeyError: 'results'
Initializing:  40%|████████████████████████████                                          | 2/5 [00:01<00:02,  1.36it/s]
```

Also, I tried the new login function and it couldn't grab any follows. There was no list generated, and the program would just stop running without crashing.

**Comment by Sydiepus** [comment]
hello, i have a question what do you really mean with follows ?   
the script is working fine for me it's grabbing the mangas in my library [here](https://mangadex.org/titles/follows) did you supplement the right argument ?    
a change to the api broke the script it should be fixed now.

**Comment by Sydiepus** [comment]
no activity.
