### ISSUE TITLE
Timeouted from mangadex

### ISSUE THREAD

**Issue by linus727** [Sydiepus/mangadex-py#4]
I just encountered this error and it's very persistent. Is it because of a timeout from mangadexs side? My internet connection should be fine. This occurred after I wanted to restart a manga download that already progressed to the 30th chapter and after "scanning" up to the 16th chapter it threw this error which wouldn't go away. Maybe it's not limiting the requests for 0.25 sec when getting the chapters and checking if they are already downloaded?

```

C:\Users\Linus\Desktop\Mangadex\mangadex-py-master>python mangadex-py.py -F follow.txt -t 4
getting uuid.
fetching manga info 'Title' 'description' 'status' based on your language setting.
No altTitles with that language found; using default title.
fetching chapters info 'available languages' 'available volumes if any' 'available chapters' 'total chapters (language independent)'.
Traceback (most recent call last):
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0392FC10>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.mangadex.org', port=443): Max retries exceeded with url: /manga/0f237a5f-07ad-4e43-bbd9-2a320694434d/feed?order%5Bchapter%5D=asc&order%5Bvolume%5D=asc&limit=500&offset=0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0392FC10>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex-py.py", line 4, in <module>
    main()
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\util.py", line 16, in main
    file_main(args.File, langwithindex, args.quality_mode, args.destination, args.max_threads)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\file_main.py", line 11, in file_main
    main(url_name[0], langWithIndex, quality_mode, Manga_main_dir, thread)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\main.py", line 15, in main
    language, volumes, chapters, totalchap = chapter.get_manga_chapters_info(uuid)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\chapters.py", line 67, in get_manga_chapters_info
    resp = requests.get(f"{api_url_manga}{uuid}/feed?order[chapter]=asc&order[volume]=asc&limit=500&offset={offset}").json()
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.mangadex.org', port=443): Max retries exceeded with url: /manga/0f237a5f-07ad-4e43-bbd9-2a320694434d/feed?order%5Bchapter%5D=asc&order%5Bvolume%5D=asc&limit=500&offset=0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0392FC10>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat'))
```

**Comment by Sydiepus** [comment]
yes you're right i didn't limit this request this could be the problem i'll limit it right away.

**Comment by Sydiepus** [comment]
not sure why it closed the issue but i limited the request.
