### ISSUE TITLE
Error with mutliple scanlations

### ISSUE THREAD

**Issue by linus727** [Sydiepus/mangadex-py#5]
Ok the download can be resumed now with the fix :) But for this chapter 31.5 from the following manga, I still get this error:
https://mangadex.org/title/0f237a5f-07ad-4e43-bbd9-2a320694434d

```
skipping chapter-30.zip
using threads.
progress bar for threaded download broken.
100%|████████████████████████████████████████████████████████████████████████████████| 45/45 [00:00<00:00, 2223.37it/s]
zipping chapter folder.
2 scanlation for chapter-31.5 found, selecting the 'best one'.
Traceback (most recent call last):
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex-py.py", line 4, in <module>
    main()
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\util.py", line 16, in main
    file_main(args.File, langwithindex, args.quality_mode, args.destination, args.max_threads)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\file_main.py", line 11, in file_main
    main(url_name[0], langWithIndex, quality_mode, Manga_main_dir, thread)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\main.py", line 22, in main
    download.main(title, chap_list, desc, status, quality_mode, base_url, Manga_main_dir, thread)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\download.py", line 56, in main
    images_link = get_images_links(chap_img, base_url)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\chapters.py", line 40, in get_images_links
    chap_hash = i[1]
IndexError: list index out of range
```

**Comment by Sydiepus** [comment]
let me check.
