### ISSUE TITLE
Not supported characters in the manga name and the file structur 

### ISSUE THREAD

**Issue by linus727** [Sydiepus/mangadex-py#6]
Hi i found a bug where under windows the folder cant be created because there are unsupported characters in the manga name string. 
So these characters are important to be replaced NUL, \, /, :, *, ?, ", <, >, |

https://stackoverflow.com/questions/4814040/allowed-characters-in-filename

````
getting uuid.
fetching manga info 'Title' 'description' 'status' based on your language setting.
No altTitles with that language found; using default title.
fetching chapters info 'available languages' 'available volumes if any' 'available chapters' 'total chapters (language independent)'.
-------------------------------------------
Ore no Genjitsu wa Ren’ai Game?? ka to Omottara Inochigake no Game datta
-------------------------------------------
fetching 'chapter list by language' 'total chapters by language.'
found 209 out of 327 for en
getting a server url to download the images from.
starting download
Traceback (most recent call last):
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex-py.py", line 4, in <module>
    main()
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\util.py", line 16, in main
    file_main(args.File, langwithindex, args.quality_mode, args.destination, args.max_threads)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\file_main.py", line 11, in file_main
    main(url_name[0], langWithIndex, quality_mode, Manga_main_dir, thread)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\main.py", line 25, in main
    download.main(title, chap_list, desc, status, quality_mode, base_url, Manga_main_dir, thread)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\download.py", line 47, in main
    create_manga_dir(manga_title, Manga_main_dir)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\fs.py", line 16, in create_manga_dir
    os.makedirs(os.path.join(current_working_dir, Manga_main_dir, manga_title))
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python39-32\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'C:\\Users\\Linus\\Desktop\\Mangadex\\mangadex-py-master\\Manga\\Ore no Genjitsu wa Ren’ai Game?? ka to Omottara Inochigake no Game datta'
````

**Comment by Sydiepus** [comment]
i'll fix it right away.

**Comment by Sydiepus** [comment]
should be fixed.

**Comment by linus727** [comment]
I am still getting this error, even with the fix:

```
skipping chapter-28.3.zip
getting uuid.
fetching manga info 'Title' 'description' 'status' based on your language setting.
No altTitles with that language found; using default title.
fetching chapters info 'available languages' 'available volumes if any' 'available chapters' 'total chapters (language independent)'.
fetching 'chapter list by language' 'total chapters by language.'
found 209 out of 327 for en
getting a server url to download the images from.
starting download
writing json
Traceback (most recent call last):
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex-py.py", line 4, in <module>
    main()
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\util.py", line 16, in main
    file_main(args.File, langwithindex, args.quality_mode, args.destination, args.max_threads)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\file_main.py", line 11, in file_main
    main(url_name[0], langWithIndex, quality_mode, Manga_main_dir, thread)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\main.py", line 22, in main
    download.main(title, chap_list, desc, status, quality_mode, base_url, Manga_main_dir, thread)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\download.py", line 47, in main
    write_series_json(manga_title, description, status, Manga_main_dir)
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-py-master\mangadex_py\fs.py", line 92, in write_series_json
    with open(series_json, "w", encoding='utf-8') as f :
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Linus\\Desktop\\Mangadex\\mangadex-py-master\\Manga\\Ore no Genjitsu wa Ren’ai Game?? ka to Omottara Inochigake no Game datta\\series.json'
```

**Comment by Sydiepus** [comment]
now the filtered title will be used globally can you check if it's working ?

**Comment by linus727** [comment]
It is working now!

**Comment by Sydiepus** [comment]
okay i'll close the issue.
